# Sidekiq Cron Jobs Configuration
# This file defines scheduled jobs that will be processed by Sidekiq

disbursement_processing:
  cron: '0 3 * * *' # Every day at 3:00 AM
  class: 'DisbursementProcessingJob'
