# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ActionMailer::Base::Mail::Message; end
module ActionMailer::Collector; end
module SyntaxTree::Haml; end
module SyntaxTree::Haml::Format::Formatter; end
module SyntaxTree::RBS; end
module SyntaxTree::RBS::Formatter; end
module T::Private::Methods::Signature; end
